# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LogViewer(5).ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QVBoxLayout, QHBoxLayout, QPushButton, QLabel, QLineEdit, QTextEdit, \
    QFileDialog
from PyQt5.QtCore import QThread, pyqtSignal
import sys
import os


# 自定义线程类
class FileReadThread(QThread):
    contentReady = pyqtSignal(str)

    def __init__(self, file_path):
        super().__init__()
        self.file_path = file_path

    def run(self):
        try:
            with open(self.file_path, "r") as file:
                content = file.read()
            self.contentReady.emit(content)
        except Exception as e:
            self.contentReady.emit(str(e))


class LogViewer(object):
    def setupUi(self, Form):
        Form.setObjectName("LogViewer")
        Form.resize(540, 420)
        Form.setMinimumSize(QtCore.QSize(540, 420))
        Form.setStyleSheet("#LogViewer{\n"
                           "    border-image: url(./img/LogViewer_BG.jpg);\n"
                           "}\n"
                           "\n"
                           "\n"
                           "#textEdit{\n"
                           "        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #cc03070e, stop:1 #aa267ab8);\n"
                           "    border-radius: 5px;\n"
                           "    border:2px solid #4bbdda;\n"
                           "}\n"
                           "\n"
                           "#label{\n"
                           "    color: #4bbdda;\n"
                           "    font: 9pt \"Arial\";\n"
                           "    font-weight: bold;\n"
                           "}\n"
                           "\n"
                           "#lineEdit{\n"
                           "    border: none;\n"
                           "    background: #00ffffff;\n"
                           "    border-bottom-style: solid;\n"
                           "    border-bottom-width: 1px;\n"
                           "    border-bottom-color: #abcdef;\n"
                           "    color: #fff;\n"
                           "}\n"
                           "\n"
                           "QPushButton{\n"
                           "    font: 9pt \"Arial\";\n"
                           "    font-weight: bold;\n"
                           "    color: #4bbdda;\n"
                           "}\n"
                           "\n"
                           "QPushButton{\n"
                           "    background-color:  qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(1, 32, 66, 255), stop:1 #aa4bbdda);\n"
                           "    border-radius: 5px;\n"
                           "    padding: 10px;\n"
                           "\n"
                           "}\n"
                           "\n"
                           "QPushButton:hover{\n"
                           "    background-color: #789abc;\n"
                           "}\n"
                           "\n"
                           "QPushButton:pressed{\n"
                           "    background-color: #89abcd;\n"
                           "}\n"
                           "\n"
                           "")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(11)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setStyleSheet("    color: #ddd;\n"
                                    "    padding: 10px 20px;    \n"
                                    "    font: 9pt \"Arial\";")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.connect_Event()
        self.Form = Form  # 在这里保存 Form 对象

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("LogViewer", "LogViewer"))
        self.label.setText(_translate("LogViewer", "File Path"))
        self.pushButton.setText(_translate("LogViewer", "Load File"))
        self.pushButton_2.setText(_translate("LogViewer", "Refresh"))
        self.textEdit.setHtml(_translate("LogViewer",
                                         "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                         "p, li { white-space: pre-wrap; }\n"
                                         "</style></head><body style=\" font-family:\'Arial\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                         "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))

    def connect_Event(self):
        self.pushButton.clicked.connect(self.selectFile)
        self.pushButton_2.clicked.connect(self.Refresh)

    def Refresh(self):
        # 获取当前lineEdit中的文件路径
        file_path = self.lineEdit.text()

        # 检查路径是否为空或文件是否存在
        if file_path and os.path.exists(file_path):
            self.startReadFile(file_path)
        else:
            # 可以在这里处理错误情况，比如显示一个错误消息
            print("Invalid file path")
    def selectFile(self):
        file_dialog = QFileDialog(self.Form)
        file_dialog.setFileMode(QFileDialog.ExistingFile)
        file_dialog.setOption(QFileDialog.DontUseNativeDialog)
        file_dialog.setNameFilter("All Files (*)")
        if file_dialog.exec_():
            file_path = file_dialog.selectedFiles()[0]
            self.lineEdit.setText(file_path)
            self.startReadFile(file_path)

    def startReadFile(self, file_path):
        self.thread = FileReadThread(file_path)
        self.thread.contentReady.connect(self.onContentReady)
        self.thread.start()

    def onContentReady(self, content):
        self.textEdit.setText(content)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = LogViewer()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
